=begin
#Replicate HTTP API

#A web service for running Replicate models

The version of the OpenAPI document: 1.0.0-a1
Contact: team@replicate.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Replicate::TrainingResponseMetrics
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Replicate::TrainingResponseMetrics do
  let(:instance) { Replicate::TrainingResponseMetrics.new }

  describe 'test an instance of TrainingResponseMetrics' do
    it 'should create an instance of TrainingResponseMetrics' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Replicate::TrainingResponseMetrics)
    end
  end

  describe 'test attribute "predict_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
