=begin
#Replicate HTTP API

#A web service for running Replicate models

The version of the OpenAPI document: 1.0.0-a1
Contact: team@replicate.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

# Common files
require 'replicate-openapi-rb/api_client'
require 'replicate-openapi-rb/api_error'
require 'replicate-openapi-rb/version'
require 'replicate-openapi-rb/configuration'

# Models
require 'replicate-openapi-rb/models/api_response'
require 'replicate-openapi-rb/models/api_response_input'
require 'replicate-openapi-rb/models/api_response_urls'
require 'replicate-openapi-rb/models/hardware_list200_response_inner'
require 'replicate-openapi-rb/models/models_create_request'
require 'replicate-openapi-rb/models/predictions_create_request'
require 'replicate-openapi-rb/models/trainings_create_request'

# APIs
require 'replicate-openapi-rb/api/default_api'

module Replicate
  class << self
    # Customize default settings for the SDK using block.
    #   Replicate.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
